// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYtrt_9cdOCZ8cKxj-KeAwcZ7mDtOjI9U',
    appId: '1:882238690514:web:4a3ed61c4c6a454554890b',
    messagingSenderId: '882238690514',
    projectId: 'shopping-bd-ingsft',
    authDomain: 'shopping-bd-ingsft.firebaseapp.com',
    storageBucket: 'shopping-bd-ingsft.appspot.com',
    measurementId: 'G-FL8NHR06CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUvwqAOu_k_e3Q2vN4cWblGfBDPwXEdbE',
    appId: '1:882238690514:android:f934300bbfbc2b7354890b',
    messagingSenderId: '882238690514',
    projectId: 'shopping-bd-ingsft',
    storageBucket: 'shopping-bd-ingsft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKeAfuxK763DiKY4SdmwJIeaCd5KNmiNA',
    appId: '1:882238690514:ios:9a4069f47fa910d554890b',
    messagingSenderId: '882238690514',
    projectId: 'shopping-bd-ingsft',
    storageBucket: 'shopping-bd-ingsft.appspot.com',
    iosClientId: '882238690514-nql0cl7ekvq3plmnpf1ltauo4f314b4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKeAfuxK763DiKY4SdmwJIeaCd5KNmiNA',
    appId: '1:882238690514:ios:9a4069f47fa910d554890b',
    messagingSenderId: '882238690514',
    projectId: 'shopping-bd-ingsft',
    storageBucket: 'shopping-bd-ingsft.appspot.com',
    iosClientId: '882238690514-nql0cl7ekvq3plmnpf1ltauo4f314b4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoFinal',
  );
}
